"""Add take_profit fields to Position table

Revision ID: 3896c8d80d53
Revises: 9f2e5db38457
Create Date: 2025-08-13 10:25:29.599649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3896c8d80d53'
down_revision: Union[str, Sequence[str], None] = '9f2e5db38457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('take_profit_order_id', sa.String(), nullable=True))
    op.add_column('positions', sa.Column('take_profit_price', sa.Numeric(precision=18, scale=8), nullable=True))
    op.create_unique_constraint(None, 'positions', ['take_profit_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='unique')
    op.drop_column('positions', 'take_profit_price')
    op.drop_column('positions', 'take_profit_order_id')
    # ### end Alembic commands ###
