"""Add suggested_tp1 column to analysis_results

Revision ID: 45acc202bd8f
Revises: e5acec3cd5ab
Create Date: 2025-07-22 10:38:21.939354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45acc202bd8f'
down_revision: Union[str, Sequence[str], None] = 'e5acec3cd5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('suggested_tp1', sa.Numeric(precision=18, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'suggested_tp1')
    # ### end Alembic commands ###
