"""Create initial tables for analysis, symbols, and strategies

Revision ID: 66e57304da2a
Revises: 
Create Date: 2025-07-11 16:07:48.058453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66e57304da2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_index(op.f('ix_strategies_strategy_name'), 'strategies', ['strategy_name'], unique=True)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=True)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('composite_score', sa.Integer(), nullable=True),
    sa.Column('overall_signal', sa.String(), nullable=True),
    sa.Column('suggested_sl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('suggested_tp', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('llm_queried', sa.Boolean(), nullable=False),
    sa.Column('llm_analysis', sa.Text(), nullable=True),
    sa.Column('indicator_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_strategy_id'), 'analysis_results', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_symbol_id'), 'analysis_results', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_timestamp'), 'analysis_results', ['timestamp'], unique=False)
    op.create_index('ix_analysis_results_timestamp_desc', 'analysis_results', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_results_timestamp_desc', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_timestamp'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_symbol_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_strategy_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_strategies_strategy_name'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    # ### end Alembic commands ###
